title: Aswendt Lab
description: Website of the Aswendt Laboratory, Neurology, University Cologne, Germany.
theme: minima

url: "https://aswendtlab.github.io/"
baseurl: "/"
repository: "Aswendt-Lab/aswendtlab.github.io"

show_menu: true
show_footer: true
google_analytics: false

docs_list_title: List of Contents
docs:
  - title: Home
    url: 
  
  - title: Projects
    url: Projects.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag

github:
  is_project_page: false

exclude:
  - gemfiles/
  - Gemfile*
  - README.md
